version: "3.7"

volumes:
  data:
    external: true
    name: rinnegan-data

networks:
  backend:
    external: true
    name: rinnegan-database

services:
  postgres:
    container_name: rinnegan-postgres
    image: rinnegan-postgres
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - rinnegan-data:/var/lib/postgresql/data
    build:
      context: .
