version: "3.7"

volumes:
  data:
    external: true
    name: rinnegan-data

networks:
  database:
    external: true
    name: rinnegan-database
  registry:
    external: true
    name: "rinnegan-registry"

services:
  postgres:
    container_name: rinnegan-postgres
    image: rinnegan-postgres
    env_file:
      - .env
    networks:
      - database
      - registry
    volumes:
      - data:/var/lib/postgresql/data
    build:
      context: .
