version: "3.7"

volumes:
  data:
    external: true
    name: rinnegan-data

networks:
  backend:
    external: true
    name: rinnegan-backend

services:
  postgres:
    container_name: rinnegan-postgres
    image: rinnegan-postgres
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data
    build:
      context: .
