name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: rinnegan-postgres

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: |
          docker build --compress --tag rinnegan-postgres .

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get branch name
        id: branch
        run: |
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Tag and push the image
        run: |
          BRANCH=`echo ${{ steps.branch.output.short_ref }}`
          NEW_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$BRANCH

          docker tag $IMAGE_NAME $NEW_IMAGE_NAME

          docker push $NEW_IMAGE_NAME
